### ISSUE TITLE
tokenizers from..?

### ISSUE THREAD

**Issue by Eunsik-Shin** [qwertyman30/melody-conditioned-lyrics-generation#1]
you load and use tokenizers in the "create dataset.ipynb", but these are not included in the repository. Could you tell me where I can find or make the tokenizers you used?

**Comment by qwertyman30** [comment]
in the create dataset notebook, you can ignore cells 2-4 and run the notebook to create a new set of tokenizers.. the code to save the tokenizers is at the end.. the cells 2-4 are needed if you have already created the tokenizers and want to create the dataset again.. will update the notebook with these comments.

**Comment by Eunsik-Shin** [comment]
Thank you for the quick reply!
It was a simple problem after all.
I should have looked at the .ipynb file till the end before I asked...
